site_name: Homepage
nav:
  - Home: index.md
  - Notes: 
    - Lecture Notes: 
      - STAT 541 Statistics for Leaning: 
        - Week1: notes/lecture_notes/stat541_week1.md
        - Week2: notes/lecture_notes/stat541_week2.md
    - Python: notes/naming_conventions.md 
    - Comparison Theorems in Riemann Geometry: 
      - Preliminaries to Comparison Theorems: notes/comparison_thm/preliminaries.md
      - Comparison Theorem: notes/comparison_thm/comp_thm.md
      - Comparison Theorems and Application: notes/comparison_thm/comp_thm_app.md
  - Suggestions/Tricks/Skills: 
    - Compare Credit Cards: suggestions/creditcardcomp.md
    - Acrobat 自动添加书签: suggestions/acrobatbookmark.md

theme: 
  name: material
  icon:
    annotation: material/chevron-right-circle

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

  