site_name: Mysite
nav:
  - Home: index.md
  - About: about.md
  - Notes: 
    - Lecture Notes: 
      - STAT 541 Statistics for Leaning: 
        - Week1: notes\lecture_notes\stat541_week1.md
        - Week2: notes\lecture_notes\stat541_week2.md
    - Learning Python: notes\naming_conventions.md
    - Life in Edmonton: notes\02-CreditCardAdvice.pdf

theme: 
  name: material
  icon:
    annotation: material/chevron-right-circle

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.superfences



extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

  